version: '2'

services:
  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME={{openldap_admin_username}}
      - LDAP_ADMIN_PASSWORD={{openldap_admin_password}}
      - LDAP_ROOT={{openldap_root}}
      # - LDAP_USER_DC=People
      # - LDAP_GROUP=Group
    networks:
      - int-net
    volumes:
      - {{openldap_home}}:/bitnami/openldap # Pour la persistance des données

networks:
  int-net: 
